logger:
  enable: true
  pretty_backtrace: true
  level: debug
  format: compact

server:
  port: 5120
  binding: {{ get_env(name="SERVER_BINDING", default="127.0.0.1") }}
  host: {{ get_env(name="SERVER_HOST", default="http://localhost") }}
  middlewares:
    fallback:
      enable: false
    static:
      enable: true
      must_exist: true
      precompressed: false
      folder:
        uri: /
        path: frontend/dist
      fallback: frontend/dist/index.html

workers:
  mode: BackgroundQueue

queue:
  kind: Redis
  uri: {{ get_env(name="REDIS_URL") }}
  dangerously_flush: false
  num_workers: 2

mailer:
  smtp:
    enable: true
    host: smtp.resend.com
    port: 2587
    secure: true
    auth:
      user: resend
      password: {{ get_env(name="RESEND_API_KEY") }}
  from: {{ get_env(name="MAILER_FROM", default="onboarding@resend.dev") }}

database:
  uri: {{ get_env(name="DATABASE_URL") }}
  enable_logging: true
  min_connections: 1
  max_connections: 10
  auto_migrate: true
  connect_timeout: {{ get_env(name="DB_CONNECT_TIMEOUT", default="5") }}
  idle_timeout: {{ get_env(name="DB_IDLE_TIMEOUT", default="300") }}

auth:
  jwt:
    secret: {{ get_env(name="JWT_SECRET") }}
    expiration: {{ get_env(name="JWT_EXPIRATION", default="604800") }}
  registration:
    email_verification_required: true